services:
  frontend:
    env_file:
      - path: .env
    build:
      context: .
      target: final
    ports:
      - 80:80
    environment:
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
      - REACT_APP_API_URL=${REACT_APP_SENTRY_DSN}

