# fly.toml app configuration file generated for klotski on 2024-06-08T23:01:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'klotski'
primary_region = 'ord'

[build]

[env]
  REACT_APP_API_URL = 'https://klotski-api.internal'
  REACT_APP_SENTRY_DSN = 'https://a977ecdf115d89dd65c9bbefce9b8931@o4505959535280128.ingest.us.sentry.io/4506888878161920'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
